### ISSUE TITLE
Error importing modules

### ISSUE THREAD

**Issue by phsgoes** [jucesarsilva/vuetify-masks-br#2]
Dear friend,

As I installed your package and configured my main.js file, I received this error message:

These relative modules were not found:

* ./node_modules/vue-convenia-util/src/helpers in ./node_modules/vuetify-masks-br/index.js
* ./node_modules/vue-convenia-util/src/validators in ./node_modules/vuetify-masks-br/index.js

Any idea about this matter?

**Comment by jucesarsilva** [comment]
Hi phsgoes, 

It's my first publish NPM package, so i did something wrong with internal's dependencies.
Go inside de folder vuetify-maks-br and run the command `npm i`, that´s must work!

I'll fix that soon, Tks!

**Comment by jucesarsilva** [comment]
@VitorLuizC tks for help with project structure to npm publish. @phsgoes the package has been updated on npm, it's should work now.

**Comment by phsgoes** [comment]
> @VitorLuizC tks for help with project structure to npm publish. @phsgoes the package has been updated on npm, it's should work now.

It's working perfectly now. Thanks a lot!
